#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout (rgba32f, binding = 0) uniform image3D result_values;
layout (rgba32f, binding = 1) uniform image3D result_normals;

#define n_balls 10

uniform vec3 positions[n_balls];
uniform vec3 colors[n_balls];
uniform float radiuses[n_balls];

void main() {
    ivec3 texel_index = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 grid_size = imageSize(result_values);
    vec3 point = vec3(
        2.0 * texel_index.x / grid_size.x - 1, 
        2.0 * texel_index.y / grid_size.y - 1, 
        2.0 * texel_index.z / grid_size.z - 1
    );

    float values[n_balls];
    vec4 result_value = vec4(0.0);
    vec4 result_normal = vec4(0.0);

    for (int i = 0; i < n_balls; ++i) {
        float dist = length(point - positions[i]);

        // function value
        values[i] = exp(-dist / radiuses[i]);
        result_value.w += values[i];
        
        // function gradient (= normal)
        vec3 grad = (point - positions[i]) * values[i] / (radiuses[i] * dist);
        result_normal += vec4(grad, 0.0);
    }

    for (int i = 0; i < n_balls; ++i)
        result_value.xyz += colors[i] * (values[i] / result_value.w);
    
    imageStore(result_values, texel_index, result_value);
    imageStore(result_normals, texel_index, result_normal);
}